---
# Installs the ownCloud personal cloud software.

- name: Install ownCloud dependencies
  ansible.builtin.apt:
    pkg:
    - postgresql
    - python3-psycopg2
    - php7.4-zip
    - php7.4-xml
    - php7.4-intl
    - php7.4-mbstring
    - php7.4-gd
    - php7.4-xsl
    - php7.4-curl

  tags:
    - dependencies

- name: Set password for PostgreSQL admin user
  become: true
  become_user: postgres
  postgresql_user: name={{ db_admin_username }} password={{ db_admin_password }} encrypted=yes

- name: Create database user for ownCloud
  postgresql_user: >-
    login_host=localhost
    login_user={{ db_admin_username }}
    login_password="{{ db_admin_password }}"
    name={{ owncloud_db_username }}
    password="{{ owncloud_db_password }}"
    role_attr_flags=CREATEDB state=present


- name: Ensure repository key for ownCloud is in place
  become: true
  ansible.builtin.shell:
    cmd: |
      echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/server:/10/Debian_10/ /' | 
      tee /etc/apt/sources.list.d/isv:ownCloud:server:10.list
      curl -fsSL https://download.opensuse.org/repositories/isv:ownCloud:server:10/Debian_10/Release.key | 
      gpg --dearmor | 
      tee /etc/apt/trusted.gpg.d/isv_ownCloud_server_10.gpg > /dev/null
  tags: 
    - dependencies



- name: Install owncloud
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - owncloud-complete-files



- name: Ensure ownCloud directory is in place
  file: state=directory path=/var/www/owncloud

- name: Move ownCloud data to encrypted filesystem
  command: mv /var/www/owncloud/data /decrypted/owncloud-data creates=/decrypted/owncloud-data

- name: Link ownCloud data directory to encrypted filesystem
  file: src=/decrypted/owncloud-data dest=/var/www/owncloud/data owner=www-data group=www-data state=link

- name: Configure Apache for ownCloud
  template: src=etc_apache2_sites-available_owncloud.j2 dest=/etc/apache2/sites-available/owncloud.conf group=root
  notify: restart apache

- name: Enable ownCloud site
  command: a2ensite owncloud.conf creates=/etc/apache2/sites-enabled/owncloud.conf
  notify: restart apache

- name: Install ownCloud cronjob
  cron: name="ownCloud" user="www-data" minute="*/5" job="php -f /var/www/owncloud/cron.php > /dev/null"
